theme: dark

server:
  address: 'tcp://0.0.0.0:9091'
  asset_path: /config/assets/

log:
  level: info

totp:
  issuer: wallyblanchard.com
  period: 30
  skew: 2

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: code.wallyblanchard.com
      policy: two_factor
    - domain: wallybrain.icu
      resources:
        - '^/admin'
      policy: two_factor

session:
  expiration: 8h
  inactivity: 2h
  remember_me: 30d
  cookies:
    - domain: wallyblanchard.com
      authelia_url: https://auth.wallyblanchard.com
      default_redirection_url: https://code.wallyblanchard.com
    - domain: wallybrain.icu
      authelia_url: https://auth.wallybrain.icu
      default_redirection_url: https://wallybrain.icu

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
